### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/emu#94]
Use GitHub actions to add a continuous integration pipeline

- [x] unit tests are run on every commit
- [ ] releases are automated whenever a commit is merged to master

**Comment by noahmacaskill** [comment]
I'll look to get this implemented.

**Comment by atruskie** [comment]
Cool, look for existing workflows here, maybe present me with what you find?

**Comment by noahmacaskill** [comment]
Sounds good, there's a .NET workflow I've been playing with on my fork that seems to be successfully running the tests. I'm consistently getting 19 tests failed (out of 140). Seems to have something to do with the environment they're being run in, they're passing when I run them on VS Code. Most are close to passing (with slight differences like a CRLF expected rather than just a LF), while others I can't figure out what is making them fail. Still looking into this, let me know if you have any thoughts.

**Comment by atruskie** [comment]
You can open a draft PR for a review.

If you want me to take a look at something, then include a link?.

For reference:

- the workflow for AP: https://github.com/QutEcoacoustics/audio-analysis/blob/master/.github/workflows/build.yml
  - don't overcomplicate your workflow until you need to; there are a lot of quirks in that above example
- The CRLF problem might be caused by a few things:
   - ensure line endings are checked out consistently: https://github.com/QutEcoacoustics/audio-analysis/blob/85ac7985bcddbd5bec0bbb9b83057106d1442b17/.gitattributes#L17-L18
   - normalize string from tests: https://github.com/QutEcoacoustics/audio-analysis/search?q=NormalizeToCrLf

**Comment by atruskie** [comment]
Partially addressed by #98
